### PR TITLE
Added sig-alg option to server tool to specify a sig alg

### PR DESCRIPTION
**Pull request by christianpaquin**
Added sig-alg option to server tool to specify a sig alg for the self-generated cert

### CODE REVIEW

**Comment by christianpaquin** [comment]
I'm working on the 2nd task right now. We need `EVP_PKEY_METHOD` and `EVP_PKEY_ASN1_METHOD` structs for each of our algs, but rather than creating a different file for each, I'll use the templating approach from our openssl fork.

**Comment by christianpaquin** [comment]
I removed the 2nd task, and scoped down this PR to the sig-alg option. Ready to review.

**Comment by xvzcf** [comment]
I think we should also just rename `sig-alg` to `oqs-sig-alg` and treat it as such.

**Comment by christianpaquin** [comment]
> I think we should also just rename `sig-alg` to `oqs-sig-alg` and treat it as such.

Firstly, I wouldn't name any thing with OQS in it; this is an implementation detail and it would be nice for the tool's API to be independent of OQS. Secondly, now that I think more about it, I think we should allow other signature algorithms in the tool. Right now it's a choice between classical default or OQS sigs, but we might want to run our PQ KEMs with various classical sigs (FIPS certified, different sizes matching different KEMs security levels, etc.). Leaving the name neutral would allow that.

**Comment by xvzcf** [comment]
Fair enough, I was just thinking of minimizing our footprint in `s_server`, but upon giving it some more thought I don't think there's good enough justification for that.

**Pull request merged**
