### PR TITLE
Removed picnic2 variants.

### PR DESCRIPTION
**Pull request by xvzcf**

### CODE REVIEW

**Comment by christianpaquin** [comment]
This doesn't affect the soon-to-be-released [tagged RC](https://github.com/open-quantum-safe/boringssl/tree/OQS-BoringSSL-snapshot-2020-06-rc2), right? Picnic2 should be in that one, but has been replaced by picnic3 in OQS post-v0.3

**Comment by dstebila** [comment]
> This doesn't affect the soon-to-be-released [tagged RC](https://github.com/open-quantum-safe/boringssl/tree/OQS-BoringSSL-snapshot-2020-06-rc2), right? Picnic2 should be in that one, but has been replaced by picnic3 in OQS post-v0.3

@xvzcf and I just talked about that. I think what we'll do is temporarily change OpenSSL/BoringSSL/OpenSSH CI to pin to the liboqs v0.3.0 release to make sure it still works, release those by the end of the week, and then unpin and do the changes like in this PR that sync back with live liboqs.

**Comment by baentsch** [comment]
> Do we want to add Picnic 3 L1 like in [open-quantum-safe/openssl#220](https://github.com/open-quantum-safe/openssl/pull/220)? Also need to rebase and then unpin from liboqs 0.3.0.

I second that: I'd think missing picnic3 support would also cause the [interop test to keep failing](https://app.circleci.com/pipelines/github/open-quantum-safe/openssl/449/workflows/41731ea0-d31e-4626-9cdb-33de3d81d03c/jobs/2527) even if `BoringSSL` builds OK again

**Comment by christianpaquin** [comment]
We also need to add the new picnicl1full param set, and use it as picnic default (instead of picnicl1fs). I did that on OpenSSL's [PR 224](https://github.com/open-quantum-safe/openssl/pull/224). Would you like to add this change to this PR, or merge this one first and then I can create a new one.

**Comment by xvzcf** [comment]
> We also need to add the new picnicl1full param set, and use it as picnic default (instead of picnicl1fs). I did that on OpenSSL's [PR 224](https://github.com/open-quantum-safe/openssl/pull/224). Would you like to add this change to this PR, or merge this one first and then I can create a new one.

I'll merge this one in since the interoperability tests are currently failing, and I can open another one to track the OpenSSL PR (and we should merge both in at the same time to avoid nightly build failures).

**Comment by christianpaquin** [comment]
> I'll merge this one in since the interoperability tests are currently failing, and I can open another one to track the OpenSSL PR (and we should merge both in at the same time to avoid nightly build failures).

Ok. I'll create another PR to deal with this, we can merge both tomorrow at the same time.

**Pull request merged**
