### PR TITLE
Update to upstream 783ae72

### PR DESCRIPTION
**Pull request by pi-314159**

### CODE REVIEW

**Comment by pi-314159** [comment]
CI error: The default Go version in Ubuntu 20 is too old, we need the latest version of Go.

Can you create an image for Ubuntu 24?

**Comment by baentsch** [comment]
> CI error: The default Go version in Ubuntu 20 is too old, we need the latest version of Go.

Is there no way to add the latest Go version to that Ubuntu release?

> Can you create an image for Ubuntu 24?

This indeed makes sense; indeed it would be better to do for the complete software stack, starting [here](https://github.com/open-quantum-safe/liboqs/blob/main/PLATFORMS.md#tier-1-1): IMO it would behoove OQS to follow a tier 1 OS (Ubuntu) LTS releases' more regularly/quickly (@dstebila FYI) and not track/experience such "latest software features" pitfalls only in downstream projects.

**Comment by dstebila** [comment]
> > CI error: The default Go version in Ubuntu 20 is too old, we need the latest version of Go.
> 
> Is there no way to add the latest Go version to that Ubuntu release?
> 
> > Can you create an image for Ubuntu 24?
> 
> This indeed makes sense; indeed it would be better to do for the complete software stack, starting [here](https://github.com/open-quantum-safe/liboqs/blob/main/PLATFORMS.md#tier-1-1): IMO it would behoove OQS to follow a tier 1 OS (Ubuntu) LTS releases' more regularly/quickly (@dstebila FYI) and not track/experience such "latest software features" pitfalls only in downstream projects.

Makes sense. I wonder if there's a way in Github to have a new issue created regularly, e.g. every 6 months, reminding us to update dependencies/build environments/etc.

**Comment by baentsch** [comment]
> I wonder if there's a way in Github to have a new issue created regularly

Sounds like something for [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot)

**Comment by pi-314159** [comment]
@baentsch Please take a look at https://github.com/open-quantum-safe/ci-containers/pull/79

**Comment by baentsch** [comment]
> @baentsch Please take a look at [open-quantum-safe/ci-containers#79](https://github.com/open-quantum-safe/ci-containers/pull/79)

Done: CI tests there passed and PR merged and docker image updated. CI here then re-run -- but still failed. I then analyzed https://github.com/open-quantum-safe/ci-containers/pull/79 more closely: It does _not_ set the env vars globally but just for the `apt` command. Accordingly, this cannot work. Suggest to set env vars explicitly in the Dockerfile by using ENV command.

**Comment by pi-314159** [comment]
@baentsch Still fails... :( I'll just create a new Dockerfile for Noble

**Comment by pi-314159** [comment]
@baentsch ci still fails...

I believe one way to fix this is setting `PATH` in BoringSSL's circleci/config.yml
Anyway, I'll just create a Dockerfile for Noble

**Comment by baentsch** [comment]
> Anyway, I'll just create a Dockerfile for Noble

FWIW, I already did that to implement https://github.com/open-quantum-safe/liboqs/issues/1780 and https://github.com/open-quantum-safe/ci-containers/issues/81-- but hit some more snags, one of which is that `go` version in noble is lower that what you put into the focal PR...

**Comment by pi-314159** [comment]
> FWIW, I already did that to implement [open-quantum-safe/liboqs#1780](https://github.com/open-quantum-safe/liboqs/issues/1780) and [open-quantum-safe/ci-containers#81](https://github.com/open-quantum-safe/ci-containers/issues/81) but hit some more snags, one of which is that `go` version in noble is lower that what you put into the focal PR...

I developed on Ubuntu Noble and haven't seen any problems. The default Go version in Ubuntu Noble is 1.22.2 (compared to the latest Go, which is 1.22.3).

**Comment by pi-314159** [comment]
@baentsch CI passed :)

**Comment by pi-314159** [comment]
@baentsch Could you review this? :)

**Review by baentsch — APPROVED** [review]
Yeah -- dutifully & painstakingly reviewed all 401 files :)

**Pull request merged**
