### PR TITLE
Sync algs with liboqs and oqs-provider

### PR DESCRIPTION
**Pull request by pi-314159**

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
I'm not sure I understand this PR: This seems to be removing for example p256_falcon512: Why? In which way does this sync with liboqs?

**Comment by pi-314159** [comment]
@baentsch Although I've added hybrid signatures to OQS-BoringSSL, I prefer to keep the clienthello size small by not enabling them by default. However, we do need to test these hybrid signature algorithms. Since we only have four types—`p256_*`, `p384_*`, `p521_*`, and `rsa3072_*`—I've decided to enable one algorithm from each type for testing purposes. Specifically, I've enabled:

- p256_mldsa44
- p384_mldsa65
- p521_mldsa87
- rsa3072_falcon512

This setup is easy to remember: mldsa with elliptic curves and falcon with rsa3072. It's a clean and straightforward way to track which algorithms are enabled.

**Comment by pi-314159** [comment]
@baentsch Do you have any additional comments? If not, I'll go ahead and merge this PR. I'll update the commit message to include that "we changed the default hybrid signature algorithms."

**Comment by baentsch** [comment]
> @baentsch Do you have any additional comments? If not, I'll go ahead and merge this PR. I'll update the commit message to include that "we changed the default hybrid signature algorithms."

And that actually is the _purpose_ of the PR, no "sync with liboqs/oqsprovider", right? Wouldn't it be fair to say that this PR creates a stronger difference between oqsprovider and boringssl even? If so, should this be documented somewhere so users understand (the rationale)?

**Comment by pi-314159** [comment]
@baentsch It syncs with oqs-provider by updating the ML-KEM code points.
Anyway I'll label it as "update algorithms," and the commit message will be:
* Add CROSS
* Update ML-KEM
* Change default enabled hybrid signature algorithms

I think it's clear that oqs-boringssl supports only a subset of algorithms available in oqs-provider.

**Review by baentsch — APPROVED** [review]
OK as per 

> label it as "update algorithms," and the commit message will be:

    Add CROSS
    Update ML-KEM
    Change default enabled hybrid signature algorithms

**Pull request merged**
