### PR TITLE
The branch is still master here

### PR DESCRIPTION
**Pull request by claucece**
Or we can create a new 'main' branch.

### CODE REVIEW

**Comment by dstebila** [comment]
> Or we can create a new 'main' branch.

Yes, we were sticking with master here because the upstream BoringSSL repo still uses master.

**Comment by xvzcf** [comment]
We can merge this in and do the rename when someone has spare cycles.

**Comment by baentsch** [comment]
> We can merge this in and do the rename when someone has spare cycles.

Didn't we decide to not rename to `main` if the upstream project doesn't/didn't do that?

**Comment by dstebila** [comment]
> > We can merge this in and do the rename when someone has spare cycles.
> 
> Didn't we decide to not rename to `main` if the upstream project doesn't/didn't do that?

Yes, that's where we left it.

**Comment by xvzcf** [comment]
Ah, that slipped my mind, but I'm fine with that policy.

**Pull request merged**
